[package]
name = "ltrait-ui-lelke" # see also https://ja.wiktionary.org/wiki/lelkiismeret
version = "0.1.0"
edition = "2024"

authors = ["satler <satler@satler.dev>"]
license = "MIT"
repository = "https://github.com/ltrait/ui-lelke"
exclude = [".envrc"]

[dependencies]
ltrait = "=1.5.0"
gpui = { version = "*" }
tracing = "0.1.41"
derive_more = { version = "2.0.1", features = ["full"] } # TODO: minimize
futures = "0.3.31"
futures-timer = "3.0.3"


# TODO: remove
tokio = { version = "1.47.1", features = [
  "rt-multi-thread",
  "macros",
], optional = true }
tracing-subscriber = { version = "0.3.20", optional = true }
gpui-component = "0.2.0"

[features]
default = ["dev"]
# default = [] # TODO:
dev = ["dep:tokio", "dep:tracing-subscriber"]
